-- Run this file once in Supabase: SQL Editor > New query > Run.

create table if not exists public.words (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    word text not null,
    part_of_speech text,
    pronunciation text,
    meaning_en text not null,
    meaning_id text,
    notes text,
    favorite boolean not null default false,
    mastery_level text not null default 'New'
        check (mastery_level in ('New', 'Learning', 'Familiar', 'Mastered')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists words_user_word_unique
    on public.words (user_id, lower(word));

create table if not exists public.word_examples (
    id bigint generated by default as identity primary key,
    word_id bigint not null references public.words(id) on delete cascade,
    sentence text not null,
    translation text,
    notes text,
    created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_words_updated_at on public.words;
create trigger set_words_updated_at
before update on public.words
for each row execute function public.set_updated_at();

alter table public.words enable row level security;
alter table public.word_examples enable row level security;

drop policy if exists "Users can read own words" on public.words;
create policy "Users can read own words"
on public.words for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own words" on public.words;
create policy "Users can insert own words"
on public.words for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own words" on public.words;
create policy "Users can update own words"
on public.words for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own words" on public.words;
create policy "Users can delete own words"
on public.words for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can read own examples" on public.word_examples;
create policy "Users can read own examples"
on public.word_examples for select to authenticated
using (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

drop policy if exists "Users can insert own examples" on public.word_examples;
create policy "Users can insert own examples"
on public.word_examples for insert to authenticated
with check (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

drop policy if exists "Users can update own examples" on public.word_examples;
create policy "Users can update own examples"
on public.word_examples for update to authenticated
using (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

drop policy if exists "Users can delete own examples" on public.word_examples;
create policy "Users can delete own examples"
on public.word_examples for delete to authenticated
using (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

grant select, insert, update, delete on public.words to authenticated;
grant select, insert, update, delete on public.word_examples to authenticated;
grant usage, select on all sequences in schema public to authenticated;
