-- Initial schema for English Dictionary. Apply to a new Supabase project once.

create table if not exists public.words (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    word text not null check (char_length(btrim(word)) between 1 and 120),
    part_of_speech text,
    pronunciation text,
    meaning_en text not null check (char_length(btrim(meaning_en)) > 0),
    meaning_id text,
    notes text,
    favorite boolean not null default false,
    mastery_level text not null default 'New'
        check (mastery_level in ('New', 'Learning', 'Familiar', 'Mastered')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists words_user_word_unique
    on public.words (user_id, lower(word));

create table if not exists public.word_examples (
    id bigint generated by default as identity primary key,
    word_id bigint not null references public.words(id) on delete cascade,
    sentence text not null check (char_length(btrim(sentence)) > 0),
    translation text,
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists word_examples_word_id_idx on public.word_examples (word_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_words_updated_at on public.words;
create trigger set_words_updated_at
before update on public.words
for each row execute function public.set_updated_at();

alter table public.words enable row level security;
alter table public.word_examples enable row level security;

drop policy if exists "Users can read own words" on public.words;
create policy "Users can read own words"
on public.words for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own words" on public.words;
create policy "Users can insert own words"
on public.words for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own words" on public.words;
create policy "Users can update own words"
on public.words for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own words" on public.words;
create policy "Users can delete own words"
on public.words for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can read own examples" on public.word_examples;
create policy "Users can read own examples"
on public.word_examples for select to authenticated
using (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

drop policy if exists "Users can insert own examples" on public.word_examples;
create policy "Users can insert own examples"
on public.word_examples for insert to authenticated
with check (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

drop policy if exists "Users can update own examples" on public.word_examples;
create policy "Users can update own examples"
on public.word_examples for update to authenticated
using (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
))
with check (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

drop policy if exists "Users can delete own examples" on public.word_examples;
create policy "Users can delete own examples"
on public.word_examples for delete to authenticated
using (exists (
    select 1 from public.words
    where words.id = word_examples.word_id
      and words.user_id = (select auth.uid())
));

revoke all on public.words, public.word_examples from public, anon, authenticated;
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.words, public.word_examples to authenticated;
revoke all on sequence public.words_id_seq, public.word_examples_id_seq from public, anon, authenticated;
grant usage on sequence public.words_id_seq, public.word_examples_id_seq to authenticated;
revoke execute on function public.set_updated_at() from public, anon, authenticated;

-- A single request saves the word and all its examples in one transaction.
-- SECURITY INVOKER preserves the caller's RLS policies.
create or replace function public.save_word(p_word_id bigint, p_word jsonb, p_examples jsonb)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
    saved_id bigint;
    caller_id uuid := auth.uid();
begin
    if caller_id is null then
        raise exception 'Please log in again.' using errcode = '42501';
    end if;
    if jsonb_typeof(p_word) is distinct from 'object'
       or jsonb_typeof(p_examples) is distinct from 'array' then
        raise exception 'Invalid word or examples.' using errcode = '22023';
    end if;

    if p_word_id is null then
        insert into public.words (
            user_id, word, part_of_speech, pronunciation, meaning_en, meaning_id,
            notes, favorite, mastery_level
        ) values (
            caller_id, btrim(p_word->>'word'), nullif(btrim(p_word->>'part_of_speech'), ''),
            nullif(btrim(p_word->>'pronunciation'), ''), btrim(p_word->>'meaning_en'),
            nullif(btrim(p_word->>'meaning_id'), ''), nullif(btrim(p_word->>'notes'), ''),
            coalesce((p_word->>'favorite')::boolean, false), coalesce(p_word->>'mastery_level', 'New')
        ) returning id into saved_id;
    else
        update public.words set
            word = btrim(p_word->>'word'),
            part_of_speech = nullif(btrim(p_word->>'part_of_speech'), ''),
            pronunciation = nullif(btrim(p_word->>'pronunciation'), ''),
            meaning_en = btrim(p_word->>'meaning_en'),
            meaning_id = nullif(btrim(p_word->>'meaning_id'), ''),
            notes = nullif(btrim(p_word->>'notes'), ''),
            favorite = coalesce((p_word->>'favorite')::boolean, false),
            mastery_level = coalesce(p_word->>'mastery_level', 'New')
        where id = p_word_id and user_id = caller_id
        returning id into saved_id;
        if saved_id is null then
            raise exception 'Word not found or access denied.' using errcode = '42501';
        end if;
        delete from public.word_examples where word_id = saved_id;
    end if;

    insert into public.word_examples (word_id, sentence, translation, notes)
    select saved_id, btrim(example->>'sentence'), nullif(btrim(example->>'translation'), ''),
           nullif(btrim(example->>'notes'), '')
    from jsonb_array_elements(p_examples) with ordinality as entry(example, position)
    order by position;

    return saved_id;
end;
$$;

revoke execute on function public.save_word(bigint, jsonb, jsonb) from public, anon;
grant execute on function public.save_word(bigint, jsonb, jsonb) to authenticated;
